calling:
  samples: config/samples.tsv
  units: config/units.tsv

  reference:
    # if `path` is not set, name should just be "genome" atm.
    name: "example_ref"
    # Custom path overrides everything below that, if file exists
    # (in that case, path must match "resources/" + name + ".fasta")
    path: "resources/example_ref.fasta"
    # The first n entries of the FASTA will be considered.
    n_chromosomes: 25
    # Ensembl species name
    species: homo_sapiens
    # Ensembl release
    release: 107
    # Genome build
    build: GRCh38

    # For now, fixed to ensembl annotation in GFF3 format
    annotation:
      release: 107


  # minimum read depth (used during covered segment identification)
  min_read_depth: 2
  # minimum number of split reads (edges with less than this number will be removed from the graph)
  min_split_reads: 5
  # maximum number of plausible circular paths generated for each strongly connected component of the graph
  max_paths_per_component: 15
  # maximum deletion length which is encoded as an edge / a breakend event. Can be useful for unmapped regions in the reference.
  max_deletion_length: 10000

  filter:
    # varlociraptor fdr control
    fdr-control:
      threshold: 0.1
      local: true
      events:
        circular:
          varlociraptor:
            - present
    circles:
      min-length: 100
      max-length: 50_000_000
