samples: config/samples.tsv
units: config/units.tsv

reference:
  # Ensembl species name
  species: homo_sapiens
  # Genome build
  build: GRCh38
  # Ensembl release
  release: 107
  # for available downloads, please browse either of these views:
  # * http://repeatmasker.org/genomicDatasets/RMGenomicDatasets.html
  # * http://repeatmasker.org/genomicDatasets/RMGenomicDatasetsAlt.html
  repeat_masker_download_link: "http://www.repeatmasker.org/genomes/hg38/RepeatMasker-rm406-dfam2.0/hg38.fa.out.gz"


cyrcular:
  # minimum read depth (used during covered segment identification)
  min_read_depth: 2
  # minimum number of split reads (edges with less than this number will be removed from the graph)
  min_split_reads: 5
  # maximum number of plausible circular paths generated for each strongly connected component of the graph
  max_paths_per_component: 15
  # maximum deletion length which is encoded as an edge / a breakend event. Can be useful for unmapped regions in the reference.
  max_deletion_length: 10000

filter:
  # varlociraptor fdr control
  fdr-control:
    threshold: 0.1
    mode: local-smart
    events:
      circular:
        varlociraptor:
          - present
  circles:
    min-length: 100
    max-length: 50_000_000
