name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches_ignore: []


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .
        snakefile: workflow/Snakefile
        stagein: "mamba install -y -n snakemake --channel conda-forge pyarrow=6.0"
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: 
      - Linting
      - Formatting
    steps:
    - uses: actions/checkout@v3
    - name: Add .cargo/bin to PATH
      run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          echo "$GITHUB_HOME/.cargo/bin" >> $GITHUB_PATH
          echo "/github/home/.cargo/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/.cargo/bin" >> $GITHUB_PATH
          echo "GITHUB_HOME: $GITHUB_HOME"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_PATH: $GITHUB_PATH"
    - name: install ruget via cargo-install
      uses: baptiste0928/cargo-install@v2.0.0
      with:
        crate: ruget
        version: "^0.4"
        locked: false
    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/config/config.yaml --use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs cache"
        stagein: 'echo "GITHUB_PATH: $GITHUB_PATH"; echo "PATH: $PATH";'

    - name: Test report
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/config/config.yaml --report report.zip"
